### ISSUE TITLE
Arduino?

### ISSUE THREAD

**Issue by dgutson** [openair-collective/openair-cyan#7]
Hi,

  Could Cyan be improved with some sensor-actuator system (like Arduino), for example to control the speed of the fan, or heating the inside part of the box?
I know epiphyte uses arduino but it seems much more expensive and probably less mature. I'm asking this for the creation of a school course for kids.

**Comment by KCollins** [comment]
Hi Daniel, 
Cyan's not currently under development, and as far as I know there's no version of it that has used Arduino in the past. However, it probably is the best starting point for a school course, and any efforts to develop it further for that purpose are certainly more than welcome. Best of luck!

**Comment by dgutson** [comment]
@KCollins I tried to look for your email before to ask this there, couldn't find it.
Any chance somebody could help me to create such a course? Ideas? I don't need help with the firmware itself, but with ideas about what role it could take? Please?

**Comment by KCollins** [comment]
Come join the OpenAir Discord! https://openaircollective.com/join/
There will be likeminded folks there. Sounds like a worthy effort!
